### ISSUE TITLE
which ntp monitor?

### ISSUE THREAD

**Issue by mfuhrmann** [opennms-config-modules/ntp#1]
is it possible to use this one?
http://docs.opennms.org/opennms/releases/18.0.2/guide-admin/guide-admin.html#_ntpmonitor
instead of org.opennms.netmgt.poller.monitors.HostResourceSwRunMonitor

**Comment by indigo423** [comment]
The NTP monitor is a little bit more specific about testing a NTP Server. You probably want to run the performance graphs also on servers running the NTP client which run the ntp process which is not exposed on the network.
